name: delyo
description: Padel tracking app
publish_to: 'none'

version: 1.1.1+4

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^2.4.9

  # Local persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Date & time formatting
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

  # App icons
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/delyo_icon.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icon/
